context:
  name: cramjam
  version: '2.8.3'

package:
  name: ${{ name }}
  version: ${{ version }}

source:
- url: https://files.pythonhosted.org/packages/0d/f2/a7c127e61dcb7878f3ec5bf07fbf472805ea8108fd63335a51ab0bd1a432/cramjam-2.8.3.tar.gz
  sha256: 6b1fa0a6ea8183831d04572597c182bd6cece62d583a36cde1e6a86e72ce2389

build:
  number: 0

requirements:
  build:
    - cross-python_${{target_platform}}
    - cffi == 1.15.1
    - openssl
    - setuptools-rust
    - rust
    - maturin
    - typing_extensions

  host:
    - python
    - openssl
    - cffi == 1.15.1
    - typing_extensions
  run:
    - cffi == 1.15.1
    - typing_extensions
    
